#!/bin/sh

make KDIR="/home/lars/spica/new_kernel/SM-kernel/" CFLAGS="-Ofast \
                -marm \
                -march=armv6zk \
                -mtune=arm1176jzf-s \
                -mfpu=vfp \
                -mfloat-abi=softfp \
                -floop-interchange \
                -floop-strip-mine \
                -floop-block \
                -funsafe-loop-optimizations \
                -funsafe-math-optimizations \
                --param l1-cache-size=16 \
                --param l1-cache-line-size=32 \
                --param simultaneous-prefetches=6 \
                --param prefetch-latency=400"
cp *.ko /home/lars/spica/new_kernel/initramfs/lib/modules/
