#!/bin/sh

make KDIR=/home/lukasz/i5700.2/kernel/v6 CFLAGS="-O3 -marm -mfpu=vfp -mtune=arm1176jzf-s"
/home/lukasz/ctng/opt/arm-spica-linux-uclibcgnueabi/bin/arm-spica-linux-uclibcgnueabi-strip --strip-unneeded *.ko
cp *.ko /home/lukasz/i5700.2/i5700-initramfs-froyo-2.6.29.6/lib/modules


