#!/bin/sh

make KDIR=/home/ch33kybutt/kernel/i5700-kernel CFLAGS="-O3 -marm -mfpu=vfp -mtune=arm1176jzf-s"
/opt/ctng/bin/arm-spica-linux-uclibcgnueabi-strip --strip-unneeded *.ko
cp *.ko /home/ch33kybutt/kernel/i5700-initramfs-froyo-2.6.29.6/lib/modules
